title: Sonika Uppalapati
logo: /assets/profile.jpg
description: Data Analyst & AI Enthusiast | Data-Driven Storyteller | Harnessing data to drive business growth | Turning Data into Insights | AI Prompter | Ex-TCS Analyst | Join my 13K+ followers for Data Innovations 🚀
show_downloads: true
theme: jekyll-theme-minimal
