title: Sonika Uppalapati
logo: /assets/profile.jpg
description: Data Analyst & AI Enthusiast | Data-Driven Storyteller | Turning Data into Insights | AI Prompter | Ex-TCS Analyst | Join my 13K+ followers on LinkedIn 🚀
show_downloads: true
theme: jekyll-theme-minimal
